// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: VerificationLongToken.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VerificationLongToken_VerificationLongToken_FullMethodName = "/VerificationLongToken.VerificationLongToken/VerificationLongToken"
)

// VerificationLongTokenClient is the client API for VerificationLongToken service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerificationLongTokenClient interface {
	VerificationLongToken(ctx context.Context, in *VerificationLongTokenRequest, opts ...grpc.CallOption) (*VerificationLongTokenResponse, error)
}

type verificationLongTokenClient struct {
	cc grpc.ClientConnInterface
}

func NewVerificationLongTokenClient(cc grpc.ClientConnInterface) VerificationLongTokenClient {
	return &verificationLongTokenClient{cc}
}

func (c *verificationLongTokenClient) VerificationLongToken(ctx context.Context, in *VerificationLongTokenRequest, opts ...grpc.CallOption) (*VerificationLongTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerificationLongTokenResponse)
	err := c.cc.Invoke(ctx, VerificationLongToken_VerificationLongToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerificationLongTokenServer is the server API for VerificationLongToken service.
// All implementations must embed UnimplementedVerificationLongTokenServer
// for forward compatibility.
type VerificationLongTokenServer interface {
	VerificationLongToken(context.Context, *VerificationLongTokenRequest) (*VerificationLongTokenResponse, error)
	mustEmbedUnimplementedVerificationLongTokenServer()
}

// UnimplementedVerificationLongTokenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerificationLongTokenServer struct{}

func (UnimplementedVerificationLongTokenServer) VerificationLongToken(context.Context, *VerificationLongTokenRequest) (*VerificationLongTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerificationLongToken not implemented")
}
func (UnimplementedVerificationLongTokenServer) mustEmbedUnimplementedVerificationLongTokenServer() {}
func (UnimplementedVerificationLongTokenServer) testEmbeddedByValue()                               {}

// UnsafeVerificationLongTokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerificationLongTokenServer will
// result in compilation errors.
type UnsafeVerificationLongTokenServer interface {
	mustEmbedUnimplementedVerificationLongTokenServer()
}

func RegisterVerificationLongTokenServer(s grpc.ServiceRegistrar, srv VerificationLongTokenServer) {
	// If the following call pancis, it indicates UnimplementedVerificationLongTokenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VerificationLongToken_ServiceDesc, srv)
}

func _VerificationLongToken_VerificationLongToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationLongTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationLongTokenServer).VerificationLongToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerificationLongToken_VerificationLongToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationLongTokenServer).VerificationLongToken(ctx, req.(*VerificationLongTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerificationLongToken_ServiceDesc is the grpc.ServiceDesc for VerificationLongToken service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerificationLongToken_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VerificationLongToken.VerificationLongToken",
	HandlerType: (*VerificationLongTokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerificationLongToken",
			Handler:    _VerificationLongToken_VerificationLongToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "VerificationLongToken.proto",
}
