// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: VerificationShortToken.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VerificationShortToken_VerificationShortToken_FullMethodName = "/VerificationShortToken.VerificationShortToken/VerificationShortToken"
)

// VerificationShortTokenClient is the client API for VerificationShortToken service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerificationShortTokenClient interface {
	VerificationShortToken(ctx context.Context, in *VerificationShortTokenRequest, opts ...grpc.CallOption) (*VerificationShortTokenResponse, error)
}

type verificationShortTokenClient struct {
	cc grpc.ClientConnInterface
}

func NewVerificationShortTokenClient(cc grpc.ClientConnInterface) VerificationShortTokenClient {
	return &verificationShortTokenClient{cc}
}

func (c *verificationShortTokenClient) VerificationShortToken(ctx context.Context, in *VerificationShortTokenRequest, opts ...grpc.CallOption) (*VerificationShortTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerificationShortTokenResponse)
	err := c.cc.Invoke(ctx, VerificationShortToken_VerificationShortToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerificationShortTokenServer is the server API for VerificationShortToken service.
// All implementations must embed UnimplementedVerificationShortTokenServer
// for forward compatibility.
type VerificationShortTokenServer interface {
	VerificationShortToken(context.Context, *VerificationShortTokenRequest) (*VerificationShortTokenResponse, error)
	mustEmbedUnimplementedVerificationShortTokenServer()
}

// UnimplementedVerificationShortTokenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerificationShortTokenServer struct{}

func (UnimplementedVerificationShortTokenServer) VerificationShortToken(context.Context, *VerificationShortTokenRequest) (*VerificationShortTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerificationShortToken not implemented")
}
func (UnimplementedVerificationShortTokenServer) mustEmbedUnimplementedVerificationShortTokenServer() {
}
func (UnimplementedVerificationShortTokenServer) testEmbeddedByValue() {}

// UnsafeVerificationShortTokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerificationShortTokenServer will
// result in compilation errors.
type UnsafeVerificationShortTokenServer interface {
	mustEmbedUnimplementedVerificationShortTokenServer()
}

func RegisterVerificationShortTokenServer(s grpc.ServiceRegistrar, srv VerificationShortTokenServer) {
	// If the following call pancis, it indicates UnimplementedVerificationShortTokenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VerificationShortToken_ServiceDesc, srv)
}

func _VerificationShortToken_VerificationShortToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationShortTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationShortTokenServer).VerificationShortToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerificationShortToken_VerificationShortToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationShortTokenServer).VerificationShortToken(ctx, req.(*VerificationShortTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerificationShortToken_ServiceDesc is the grpc.ServiceDesc for VerificationShortToken service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerificationShortToken_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VerificationShortToken.VerificationShortToken",
	HandlerType: (*VerificationShortTokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerificationShortToken",
			Handler:    _VerificationShortToken_VerificationShortToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "VerificationShortToken.proto",
}
