// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.20.3
// source: CreateLongToken.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLongTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLongTokenRequest) Reset() {
	*x = CreateLongTokenRequest{}
	mi := &file_CreateLongToken_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLongTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLongTokenRequest) ProtoMessage() {}

func (x *CreateLongTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CreateLongToken_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLongTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateLongTokenRequest) Descriptor() ([]byte, []int) {
	return file_CreateLongToken_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLongTokenRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateLongTokenRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CreateLongTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongToken     string                 `protobuf:"bytes,1,opt,name=longToken,proto3" json:"longToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLongTokenResponse) Reset() {
	*x = CreateLongTokenResponse{}
	mi := &file_CreateLongToken_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLongTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLongTokenResponse) ProtoMessage() {}

func (x *CreateLongTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CreateLongToken_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLongTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateLongTokenResponse) Descriptor() ([]byte, []int) {
	return file_CreateLongToken_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLongTokenResponse) GetLongToken() string {
	if x != nil {
		return x.LongToken
	}
	return ""
}

var File_CreateLongToken_proto protoreflect.FileDescriptor

var file_CreateLongToken_proto_rawDesc = []byte{
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x46, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x37, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x79, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x66, 0x0a, 0x0f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x27, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_CreateLongToken_proto_rawDescOnce sync.Once
	file_CreateLongToken_proto_rawDescData = file_CreateLongToken_proto_rawDesc
)

func file_CreateLongToken_proto_rawDescGZIP() []byte {
	file_CreateLongToken_proto_rawDescOnce.Do(func() {
		file_CreateLongToken_proto_rawDescData = protoimpl.X.CompressGZIP(file_CreateLongToken_proto_rawDescData)
	})
	return file_CreateLongToken_proto_rawDescData
}

var file_CreateLongToken_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_CreateLongToken_proto_goTypes = []any{
	(*CreateLongTokenRequest)(nil),  // 0: CreateLongToken.CreateLongTokenRequest
	(*CreateLongTokenResponse)(nil), // 1: CreateLongToken.CreateLongTokenResponse
}
var file_CreateLongToken_proto_depIdxs = []int32{
	0, // 0: CreateLongToken.CreateLongToken.createLongToken:input_type -> CreateLongToken.CreateLongTokenRequest
	1, // 1: CreateLongToken.CreateLongToken.createLongToken:output_type -> CreateLongToken.CreateLongTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CreateLongToken_proto_init() }
func file_CreateLongToken_proto_init() {
	if File_CreateLongToken_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CreateLongToken_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CreateLongToken_proto_goTypes,
		DependencyIndexes: file_CreateLongToken_proto_depIdxs,
		MessageInfos:      file_CreateLongToken_proto_msgTypes,
	}.Build()
	File_CreateLongToken_proto = out.File
	file_CreateLongToken_proto_rawDesc = nil
	file_CreateLongToken_proto_goTypes = nil
	file_CreateLongToken_proto_depIdxs = nil
}
